# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ecd189ca3a372b77907580314a09bcf0caca45cab60c4b3f4fbb251905ceff7e1af6e152d102baf6b32a516be8e33a8ed474768dbd7ee6c1aa0b5e6da526b7

test:
  secret_key_base: 901494ee7012b5b6c657fa3d33f44063a5d4ab5f3838e9434685e714b39dc792d20ef60c7676a5a66c56c8b8a9e932f430f0405cc38c12eb04236e91abddf49e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
